export type { TSESLint } from '@typescript-eslint/utils'
export type { Linter } from 'eslint'
export { default as tseslint } from 'typescript-eslint'
export { default as eslint } from '@eslint/js'
export { default as globals } from 'globals'
